input.onButtonPressed(Button.A, function () {
    basic.clearScreen()
})
input.onButtonPressed(Button.B, function () {
    led.plot(0, 0)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(0, 0)
    led.plot(1, 0)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(1, 0)
    led.plot(2, 0)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(2, 0)
    led.plot(3, 0)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(3, 0)
    led.plot(4, 0)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(4, 0)
    led.plot(4, 1)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(4, 1)
    led.plot(3, 1)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(3, 1)
    led.plot(2, 1)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(2, 1)
    led.plot(1, 1)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(1, 1)
    led.plot(0, 1)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(0, 1)
    led.plot(0, 2)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(0, 2)
    led.plot(1, 2)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(1, 2)
    led.plot(2, 2)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(2, 2)
    led.plot(3, 2)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(3, 2)
    led.plot(4, 2)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(4, 2)
    led.plot(4, 3)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(4, 3)
    led.plot(3, 3)
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    basic.pause(200)
    led.unplot(3, 3)
})
input.onGesture(Gesture.Shake, function () {
    basic.showNumber(randint(1, 6))
})
basic.forever(function () {
	
})
